MODUL6 FRISCA/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/user', 'UserController');

Route::resource('/post', 'PostController');

Route::post('/comment', "KomentarController@addComment")->name('comment.add');

Route::get('/comment/{id}', "KomentarController@addLike")->name('comment.like');

MODUL6 FRISCA/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';

    protected $fillable = [
        'user_id', 'caption', 'image', 'likes',
    ];

    public function user()
    {
        return $this->belongsTo(\App\User::class,'user_id');
    }

    public function kometarPosts()
    {
        return $this->hasMany(\App\Komentar_Post::class,'post_id');   
    }
}

MODUL6 FRISCA/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Komentar_Post;
use Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.addpost');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = $request->file('imagePost');

        if (!$file) {
            return redirect()->route('user.index');
        }

        $file_name = $file->getClientOriginalName();
        $path = public_path("/posts/".Auth::User()->id);
        $file->move($path, $file_name);

        $posts = new Post();
        $posts->user_id = Auth::User()->id;
        $posts->caption = $request->captionPost;
        $posts->image = "/posts/".Auth::User()->id."/".$file_name;
        $posts->likes = 0;

        $posts->save();

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::with('user')->where('id', $id)->get();
        $comments = Komentar_Post::with('user')->where('post_id', $id)->get();
        return view('post.detailpost',compact('post','comments')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

MODUL6 FRISCA/resources/views/post/addpost.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-1">
        <div class="col-md-9">
            <form method="POST" action="{{route('post.store')}}"  enctype="multipart/form-data">
                {{csrf_field()}}
                <h2>Add New Post</h2>
                <p>Post Caption</p>
                <input type="text" class="form-control" name="captionPost" required><br>
                <p>Post Image</p>
                <input type="file" class="form-control-file" name="imagePost" required>
                <br>
                <button type="submit" class="btn btn-primary">Add New Post</button>
            </form>
        </div>
    </div>  
</div>
@endsection

MODUL6 FRISCA/resources/views/post/detailpost.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 text-center">
            <img src="{{asset($post[0]->image)}}" width="75%">
        </div>
        <div class="col-md-4">
            <img src="{{asset($post[0]->user->avatar)}}" width="50" style="border-radius: 50%;">
            <b> {{$post[0]->user->name}}</b> 
            <br>
            <hr>
            <p><b>{{$post[0]->user->email}}</b> {{$post[0]->caption}}</p>
            <p>
                @foreach($comments as $komentar)
                <b>{{$komentar->user->email}}</b> {{$komentar->comment}} <br>
                @endforeach
            </p>
            <hr>
            <p>
                <a href="{{ url('comment/'.$post[0]->id) }}">
                    <i class="fa fa-heart-o" style="font-size:24px; color: black;"></i>
                </a> 
                <a href="#detail_komentar">
                    <i class="fa far fa-comment-o" style="font-size:24px; color: black;"></i>
                </a>
                <b>{{$post[0]->likes}} Like</b>
            </p>
            <form action="{{route('comment.add')}}" method="POST">  
                @csrf
                <input type="hidden" name="post_id" value="{{$post[0]->id}}">
                <div class="input-group">
                    <input type="text" class="form-control" name="komentar" id="detail_komentar" required placeholder="Add a comment..">
                    <button type="submit" class="btn btn-primary" name="create_komentar" value="kirim">Send</button>
                </div>
            </form>    
        </div>
    </div>
</div>
@endsection