MODUL6 FRISCA/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/user', 'UserController');

Route::resource('/post', 'PostController');

Route::post('/comment', "KomentarController@addComment")->name('comment.add');

Route::get('/comment/{id}', "KomentarController@addLike")->name('comment.like');

MODUL6 FRISCA/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'title', 'description', 'url', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function posts()
    {
        return $this->hasMany(\App\Post::class,'user_id');
    }

    public function kometarPosts()
    {
        return $this->hasMany(\App\Komentar_Post::class,'user_id');   
    }
}

MODUL6 FRISCA/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profile = User::with('posts')->where('id', Auth::User()->id)->get();
        return view('user.viewprofile',compact('profile'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = User::where('id', Auth::User()->id)->get();
        return view('user.editprofile',compact('edit'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = $request->file('imageProfile');

        $users = User::findOrFail(Auth::User()->id);
        $users->title = $request->titleProfile;
        $users->description = $request->descriptionProfile;
        $users->url = $request->urlProfile;

        if ($file) {
            $file_name = $file->getClientOriginalName();
            $path = public_path("/avatars/".Auth::User()->id);
            $file->move($path, $file_name);
            $users->avatar = "/avatars/".Auth::User()->id."/".$file_name;
        }

        $users->save();
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

MODUL6 FRISCA/resources/views/user/editprofile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-1">
        <div class="col-md-9">
            <form method="POST" action="{{route('user.store')}}"  enctype="multipart/form-data">
                {{csrf_field()}}
                <h2>Edit Profile</h2>
                <p>Title</p>
                <input type="text" class="form-control" name="titleProfile" required value="{{$edit[0]->title}}"><br>
                <p>Discription</p>
                <input type="text" class="form-control" name="descriptionProfile" required value="{{$edit[0]->description}}"><br>
                <p>URL</p>
                <input type="text" class="form-control" name="urlProfile" required value="{{$edit[0]->url}}"><br>
                <p>Profile Image</p>
                <input type="file" class="form-control-file" name="imageProfile" accept="image/*">
                <br>
                <button type="submit" class="btn btn-primary">Save Profile</button>
            </form>
        </div>
    </div>  
</div>
@endsection

MODUL6 FRISCA/resources/views/user/viewprofile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-md-4 text-center">
            <img src="{{$profile[0]->avatar}}" width="60%">
        </div>
        <div class="col-md-6">
            <h4>{{$profile[0]->name}}</h4><br>
            <p><a href="{{ route('user.create') }}" >Edit Profile</a><br>
                <b>{{count($profile[0]->posts)}}</b> Post</p>
            <p><b>{{$profile[0]->title}}</b><br>{{$profile[0]->description}} <br><a href="{{$profile[0]->url}}" target="_blank">{{$profile[0]->url}}</a> 
            </p>
        </div>
        <div class="col-md-2 text-right">
            <a href="{{ route('post.create') }}" >Add New Post</a>
        </div>
    </div>
    <div class="row justify-content-left my-1">
        @foreach($profile[0]->posts as $post)
        <div class="col-md-4 my-3">
            <a href="{{ route('post.show', $post->id) }}"><img src="{{$post->image}}" width="100%"></a>
        </div>
        @endforeach
    </div>
</div>
@endsection